// Visual test harness for the Electron result screen (caveat 3: "the Electron
// result screen is typecheck-verified, not visually run"). Mounts the REAL <App>
// shell + <AnalysisResult> component — the same React tree the Electron renderer
// ships — in a browser tab, backed by a fully in-memory mock of the window.app
// IPC bridge and a REAL computed AnalysisRecord (generated by gensample from real
// pose frames). The Electron renderer IS Chromium, so this is a faithful render
// of the production screen; only the SQLite IPC layer is mocked.
//
// ?case=seq  -> sequence-mode report (DTW chart, phases)   [default]
// ?case=single -> single-frame report (keyUserFrame, no phases)
//
// NOT part of the shipped app.
import ReactDOM from "react-dom/client";
import App from "./App";
import { useStore } from "./store";
import "./styles.css";
import type {
  AnalysisRecord,
  AppApi,
  AppSettings,
  SavedWorkout,
} from "@shared/types";

// --- In-memory mock of the full AppApi (all 10 methods). store.refresh() calls
// listAnalyses/listWorkouts/getSettings on mount, so a partial mock would
// white-screen before AnalysisResult renders. ---
const analyses = new Map<string, AnalysisRecord>();
const workouts = new Map<string, SavedWorkout>();
let settings: AppSettings = { theme: "dark" };
const log = (...a: unknown[]) => console.log("[APPTEST mock]", ...a);

const mockApi: AppApi = {
  saveAnalysis: async (r) => { analyses.set(r.id, r); log("saveAnalysis", r.id); },
  listAnalyses: async () => [...analyses.values()],
  getAnalysis: async (id) => analyses.get(id) ?? null,
  deleteAnalysis: async (id) => { analyses.delete(id); log("deleteAnalysis", id); },
  saveWorkout: async (w) => { workouts.set(w.id, w); log("saveWorkout", w.id); },
  listWorkouts: async () => [...workouts.values()],
  deleteWorkout: async (id) => { workouts.delete(id); log("deleteWorkout", id); },
  getSettings: async () => settings,
  setSettings: async (s) => { settings = { ...settings, ...s }; return settings; },
  openExternal: async (url) => { log("openExternal", url); },
};
window.app = mockApi;

async function main() {
  const params = new URLSearchParams(location.search);
  const which = params.get("case") === "single" ? "sample_single" : "sample_seq";
  const res = await fetch(`/${which}.json`);
  if (!res.ok) throw new Error(`could not fetch /${which}.json (HTTP ${res.status}) — run: REAL_EVAL=1 npx vitest run gensample`);
  const record = (await res.json()) as AnalysisRecord;
  analyses.set(record.id, record);

  // Seed the store and route straight to the analysis screen, exactly as
  // NewAnalysis.start() does after a real run (go({ name:"analysis", record })).
  useStore.setState({
    route: { name: "analysis", record },
    analyses: [record],
    workouts: [],
    settings,
  });

  // No StrictMode: App's mount effect triggers refresh(); double-invocation would
  // just re-fetch the mock harmlessly, but we keep it single to mirror production.
  ReactDOM.createRoot(document.getElementById("root")!).render(<App />);

  // Observability hooks for the driver.
  (window as unknown as { __apptest: unknown }).__apptest = {
    case: which,
    mode: record.report.mode,
    sim: record.report.overallSimilarity,
    phases: record.report.phases.length,
    workouts: record.report.workouts.length,
    guide: !!record.report.guide,
  };
  setTimeout(() => { document.title = `APPTEST READY ${which} ${record.report.mode}`; }, 300);
}

main().catch((e) => {
  document.title = "APPTEST ERROR";
  const root = document.getElementById("root")!;
  root.textContent = `APPTEST ERROR: ${e?.stack || e}`;
  console.error("[APPTEST]", e);
});
