import { useEffect, useRef, useState } from "react";
import clsx from "clsx";
import { Check, Info, Save, ShieldCheck } from "lucide-react";
import { useStore } from "../store";
import { APP_VERSION } from "../version";

export function Settings() {
  const settings = useStore((s) => s.settings);
  const refreshSettings = useStore((s) => s.refreshSettings);

  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [saved, setSaved] = useState(false);
  const savedTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (settings) setTheme(settings.theme);
  }, [settings]);

  // Clear the "Saved" toast timer on unmount so it can't fire setState after the
  // component is gone (and replace any in-flight timer on a rapid re-save).
  useEffect(() => {
    return () => {
      if (savedTimer.current) clearTimeout(savedTimer.current);
    };
  }, []);

  const save = async () => {
    await window.app.setSettings({ theme });
    await refreshSettings();
    setSaved(true);
    if (savedTimer.current) clearTimeout(savedTimer.current);
    savedTimer.current = setTimeout(() => setSaved(false), 1500);
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="h1">Settings</h1>
        <p className="mt-2 text-ink-300">
          Your videos and analysis stay on this device — pose estimation, comparison, the
          coaching guide, and the workouts are all computed locally and free, with no API
          key. The only network use is a one-time, cached download of the open-source
          MediaPipe pose model the first time you run an analysis; your footage and data
          are never uploaded.
        </p>
      </div>

      <div className="card p-6 space-y-4">
        <div className="flex items-start gap-3">
          <ShieldCheck size={18} className="text-ok mt-0.5" />
          <div className="text-sm text-ink-200">
            <div className="font-medium text-ink-50">On-device coaching</div>
            <div className="text-ink-400 text-xs mt-1">
              The improvement guide and training workouts are generated by a built-in
              biomechanics engine directly from your joint-angle comparison — no account,
              no key, and nothing about your footage leaves your machine.
            </div>
          </div>
        </div>

        <div>
          <label className="label mb-2 block" htmlFor="theme-select">
            Theme
          </label>
          <select
            id="theme-select"
            className="input"
            value={theme}
            onChange={(e) => setTheme(e.target.value as "dark" | "light")}
          >
            <option value="dark">Dark</option>
            <option value="light">Light</option>
          </select>
        </div>

        <div className="flex items-center justify-end gap-3 pt-2">
          <div
            role="status"
            aria-live="polite"
            className={clsx(
              "text-xs text-ok flex items-center gap-1 transition-opacity duration-300",
              saved ? "opacity-100" : "opacity-0",
            )}
          >
            {saved && (
              <>
                <Check size={12} /> Saved
              </>
            )}
          </div>
          <button className="btn-primary" onClick={save}>
            <Save size={14} /> Save settings
          </button>
        </div>
      </div>

      <div className="card p-6 space-y-3">
        <div className="flex items-center gap-2">
          <Info size={18} className="text-accent-400" />
          <div className="font-medium text-ink-50">About</div>
        </div>
        <dl className="text-sm">
          <div className="flex items-center justify-between py-1.5 border-b border-white/5">
            <dt className="text-ink-400">Application</dt>
            <dd className="text-ink-200">Sport Coach — Mesh Analysis</dd>
          </div>
          <div className="flex items-center justify-between py-1.5 border-b border-white/5">
            <dt className="text-ink-400">Version</dt>
            <dd className="text-ink-200 tabular-nums">{APP_VERSION}</dd>
          </div>
          <div className="flex items-center justify-between py-1.5 border-b border-white/5">
            <dt className="text-ink-400">Pose model</dt>
            <dd className="text-ink-200">MediaPipe BlazePose (heavy)</dd>
          </div>
          <div className="flex items-center justify-between py-1.5">
            <dt className="text-ink-400">Data location</dt>
            <dd className="text-ink-200">On this device only</dd>
          </div>
        </dl>
      </div>
    </div>
  );
}
