import { useEffect, useState } from "react";
import { Check, Save, ShieldCheck } from "lucide-react";
import { useStore } from "../store";

export function Settings() {
  const settings = useStore((s) => s.settings);
  const refreshSettings = useStore((s) => s.refreshSettings);

  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (settings) setTheme(settings.theme);
  }, [settings]);

  const save = async () => {
    await window.app.setSettings({ theme });
    await refreshSettings();
    setSaved(true);
    setTimeout(() => setSaved(false), 1500);
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="h1">Settings</h1>
        <p className="mt-2 text-ink-300">
          Everything runs locally and free — pose estimation, comparison, the coaching
          guide, and the workouts are all computed on this device. No API key required
          and nothing is ever sent off your machine.
        </p>
      </div>

      <div className="card p-6 space-y-4">
        <div className="flex items-start gap-3">
          <ShieldCheck size={18} className="text-ok mt-0.5" />
          <div className="text-sm text-ink-200">
            <div className="font-medium text-ink-50">Fully offline coaching</div>
            <div className="text-ink-400 text-xs mt-1">
              The improvement guide and training workouts are generated by a built-in
              biomechanics engine directly from your joint-angle comparison — no account,
              no key, no internet.
            </div>
          </div>
        </div>

        <div>
          <div className="label mb-2">Theme</div>
          <select
            className="input"
            value={theme}
            onChange={(e) => setTheme(e.target.value as "dark" | "light")}
          >
            <option value="dark">Dark</option>
            <option value="light">Light</option>
          </select>
        </div>

        <div className="flex items-center justify-end gap-3 pt-2">
          {saved && (
            <div className="text-xs text-ok flex items-center gap-1">
              <Check size={12} /> Saved
            </div>
          )}
          <button className="btn-primary" onClick={save}>
            <Save size={14} /> Save settings
          </button>
        </div>
      </div>
    </div>
  );
}
